### PR TITLE
Build and deploy to Heroku from GH.

### PR DESCRIPTION
**Pull request by rpiaggio**
It seems Heroku's memory for builds (2.5G) is again not enough for our build.

This PR moves the build back to GitHub Actions, deploying only the static assets to Heroku.

I've consequently removed the scala and node buildpacks from Heroku.

### CODE REVIEW

**Review by cquiroz — APPROVED** [review]
Thanks for this, let's test it

**Review by toddburnside — APPROVED** [review]
LGTM. Thanks for taking care of this.

**Comment by cquiroz** [comment]
We should declare @rpiaggio master of heroku and bestow him with all the joy of handling these fixes

**Comment by toddburnside** [comment]
> We should declare @rpiaggio master of heroku and bestow him with all the joy of handling these fixes

All hail the master! 🙇‍♂️

**Pull request merged**
