### PR TITLE
Partial fix for changed to plannedTime API

### PR DESCRIPTION
**Pull request by cquiroz**
The latest change on the API related to plannedtime broke explore
This makes it work but there is still work pending to adapt to the new API, I think @hugo-vrijswijk is working on planned time in general

### CODE REVIEW

**Review by rpiaggio — APPROVED** [review]
LGTM

**Review by toddburnside — APPROVED** [review]
Looks good for a short term fix to get explore working. 👍

**Comment by swalker2m** [comment]
How are things set up?  When this is merged, does it go directly to staging?

**Comment by toddburnside** [comment]
> How are things set up? When this is merged, does it go directly to staging?

That is correct. We'll need to promote the odb when this is merged.

**Pull request merged**
