### PR TITLE
Elevation plot of multiple targets

### PR DESCRIPTION
**Pull request by rpiaggio**
image

### CODE REVIEW

**Comment by rpiaggio** [comment]
This is ready for review.

The requirement to show dashed lines for targets not associated with observations in the shown site will be implemented in a future PR.

**Comment by cquiroz** [comment]
I guess we dont support semester plots?

**Review by cquiroz — APPROVED** [review]
LGTM

**Comment by rpiaggio** [comment]
> I guess we dont support semester plots?

No. I'm not sure that is a requirement, but it could be implemented.

For the moment, the semester selector is only enabled if you choose only one target.

**Pull request merged**
