### PR TITLE
Switch to FomanticUI

### PR DESCRIPTION
**Pull request by cquiroz**
This PR switches to the SemanticUI fork. On the target editor checkboxes we can see the effect as they were marked as mini but that was not available on SemanticUI's css

image

The PR is fairly large but it is mostly about copying the updated themes

### CODE REVIEW

**Comment by cquiroz** [comment]
Ups, big increase on css size

**Comment by swalker2m** [comment]
This is the alternative that came up in the review?

**Comment by cquiroz** [comment]
Yes, this is a fork that is actively
Maintained, they've fixed a few bugs which is why the checkboxes look smaller in the screenshot and added some extras which explains the increase on css size

**Comment by rpiaggio** [comment]
Maybe it's possible to (easily) leave out the big parts that we don't use?

**Comment by cquiroz** [comment]
This looks fine in heroku, I'll merge

**Pull request merged**
