### PR TITLE
Paint visualization time in night plot

### PR DESCRIPTION
**Pull request by rpiaggio**
For the moment, duration is fixed at 1 hour since we are not computing observation time.

image

Showing only elevation and parallactic angle:

image

### CODE REVIEW

**Comment by cquiroz** [comment]
Looks very good, I wonder if we should only plot parallactic angle, @andrewwstephens

**Review by cquiroz — APPROVED** [review]
LGTM

**Comment by rpiaggio** [comment]
> Looks very good, I wonder if we should only plot parallactic angle, @andrewwstephens

I'll merge for now and we can "unpaint" the other series later.

**Comment by andrewwstephens** [comment]
I think that looks great!  :+1:

**Pull request merged**
