### PR TITLE
Proposal category groups

### PR DESCRIPTION
**Pull request by toddburnside**
image
Some additional styling may be desired for the header.

This is not a new issue, but we probably want to keep the width from resizing when longer items are selected, too.

### CODE REVIEW

**Review by cquiroz — APPROVED** [review]
The list looks great

**Comment by rpiaggio** [comment]
Looks very nice.

A very minor thing: if I click on a header, the selection doesn't change (which is the expected behavior) but the dropdown still collapses. Is there a way to avoid this?

**Review by rpiaggio — APPROVED** [review]
LGTM

**Comment by toddburnside** [comment]
> A very minor thing: if I click on a header, the selection doesn't change (which is the expected behavior) but the dropdown still collapses. Is there a way to avoid this?

I've got a couple of ideas.

**Comment by toddburnside** [comment]
> > A very minor thing: if I click on a header, the selection doesn't change (which is the expected behavior) but the dropdown still collapses. Is there a way to avoid this?
> 
> I've got a couple of ideas.

If we don't use the `pointing-events: none` it fixes this issue. However, hovering over the header did have a highlighting effect. I didn't like that, but I guess that's really a matter of personal preference. I removed `pointing-events` and set some CSS to make hovering do nothing. We can change that as desired.

**Pull request merged**
