### PR TITLE
Undo documentation

### PR DESCRIPTION
**Pull request by rpiaggio**

### CODE REVIEW

**Comment by rpiaggio** [comment]
image

I was surprised to see here that the size of the bundles is nondeterministic. Here we are just changing documentation and the size changed.

**Comment by cquiroz** [comment]
Yes they are not fully deterministic, at a minumum the text of the version changes  but there maybe something else

**Comment by rpiaggio** [comment]
Documentation is a bit more rounded now, giving a usage overview of all the aspects of the undo implementation.

Suggestions are welcome. Otherwise, I think we can merge.

**Comment by cquiroz** [comment]
Thanks a lot!

**Review by cquiroz — APPROVED** [review]
LGTM

**Pull request merged**
