### PR TITLE
Avoid overflowing with the active status toggle

### PR DESCRIPTION
**Pull request by cquiroz**
Before:
image

After:
image

### CODE REVIEW

**Comment by toddburnside** [comment]
When did these get smooshed together?
image
It seems a bit hard to read.

**Review by toddburnside — APPROVED** [review]
LGTM

**Comment by cquiroz** [comment]
Yeah I didn't want to reduce the size of the text. but tested it making it very small and the text will overflow to the next line.

**Comment by toddburnside** [comment]
> Yeah I didn't want to reduce the size of the text. but tested it making it very small and the text will overflow to the next line

Actually, I meant the fact that `GMOS-S B600` is smooshed together with `<0.1" <0.1 mag Dark Wet`. It's nothing that changed in this PR, but I just noticed it when looking at the images.

**Pull request merged**
