### PR TITLE
Show date in semester plot

### PR DESCRIPTION
**Pull request by rpiaggio**
Green line now shows the selected date, progress bar is now shown in gray.

Kapture 2023-02-20 at 11 37 13

### CODE REVIEW

**Comment by cquiroz** [comment]
Is the line on the "current" date?

**Review by cquiroz — APPROVED** [review]
LGTM

**Comment by rpiaggio** [comment]
> Is the line on the "current" date?

The line shows the selected date below.

**Comment by rpiaggio** [comment]
Revamped this so that the date shown is the visualization time, and now there's a "semester picker" in the semester view:

Kapture 2023-02-22 at 22 55 39

I also refactored the logic of `ElevationPlotSection` to streamline it.

**Review by toddburnside — APPROVED** [review]
LGTM

**Pull request merged**
