### PR TITLE
Change scalafmt.conf

### PR DESCRIPTION
**Pull request by toddburnside**
Use file from lucuma-ui

### CODE REVIEW

**Comment by rpiaggio** [comment]
I missed the comment in lucuma-ui and I see now that we lost aligning `=>`s in `match/case`s and `<-` in `for`s. Or there seems to be a low threshold to keep them aligned. It'd be cool to just get those back.

**Comment by toddburnside** [comment]
> I missed the comment in lucuma-ui and I see now that we lost aligning `=>`s in `match/case`s and `<-` in `for`s. Or there seems to be a low threshold to keep them aligned. It'd be cool to just get those back.

Yeah. It's a bit odd. For example, in ConnectionsStatus.scala some, but not all of the `=>` are aligned.

**Review by cquiroz — APPROVED** [review]
LGTM

**Comment by toddburnside** [comment]
Interestingly, it only seems to be possible to get the alignment of the `=>` and `<-` with `align.preset = most`, not with any of the individual settings. Of course, that also brings back the aligned `=`, even for definitions separated by new lines. 

Also, I like the `align.arrowEnumeratorGenerator = true` setting, which gives 

image

instead of 

image

This is something we had previously with the `most` preset, but can also be set independently.

I wonder if we should wait for the fix to https://github.com/scalameta/scalafmt/issues/2775 in https://github.com/scalameta/scalafmt/pull/2753 and go back to the `most` preset?

**Comment by cquiroz** [comment]
I also prefer the alignment inside the for loops

We can certainly wait for upstream fixes

**Comment by toddburnside** [comment]
> I also prefer the alignment inside the for loops
> 
> We can certainly wait for upstream fixes

The failure to sometimes not align the `=>` and `<-` had to do with multiline statements. `align.multiline = true` needed to be set, but that also caused the extreme alignment of the `=` even across spaces. There have been 2 PRs merged to fix the multiline issues. 

Unless someone objects, I'll close this PR and see what happens when a new version of scalafmt-core is released. I would like to compare what happens with `align.preset = most` vs what is in this PR with the addition of `align.multiline = true` and `align.arrowEnumeratorGenerator = true`.

**Comment by toddburnside** [comment]
Just a note for future work. If we use `align.preset = most` I think we can get rid of all (or at least most) of the `align.tokens` settings as they are included in `most`.

**Comment by toddburnside** [comment]
Waiting on new version of scalafmt.

**Pull request closed without merging**
