### PR TITLE
Basic Heroku CI configuration (no nginx yet)

### PR DESCRIPTION
**Pull request by rpiaggio**

### CODE REVIEW

**Comment by rpiaggio** [comment]
It's normal that Heroku CI is still failing, it doesn't have node/npm provisioning yet. It should start working after this PR is merged.

**Comment by cquiroz** [comment]
How does it know to call `fullOptJS`?

**Comment by rpiaggio** [comment]
> How does it know to call `fullOptJS`?

For CI, it doesn't. It calls `sbt test`. For deployment as a static resource, that's coming in the next PR ;)

**Comment by rpiaggio** [comment]
BTW, we can change the command we run for test in CI.

**Comment by cquiroz** [comment]
ok, then we could remove the GH Action

**Pull request merged**
