### PR TITLE
Support displaying/setting wavelength in nanometers or micrometers

### PR DESCRIPTION
**Pull request by cquiroz**

### CODE REVIEW

**Comment by rpiaggio** [comment]
Screenshot?

**Review by rpiaggio — APPROVED** [review]
LGTM.

I initially thought this requirement was to be able to set the units for each field, but that would require saving the units in the ODB.

**Comment by cquiroz** [comment]
https://github.com/user-attachments/assets/c6dcb972-d05a-48c1-92c4-8e1b53680986

**Comment by rpiaggio** [comment]
> Monosnap.screencast.2024-10-17.10-56-43.mp4

Nice

**Pull request merged**
