### PR TITLE
Remove existence checks from allGroupElements query

### PR DESCRIPTION
**Pull request by hugo-vrijswijk**
~~Alternative way to fix #3810~~

Removes the checks that are no longer needed since the backend filters out deleted groups/observations

### CODE REVIEW

**Comment by hugo-vrijswijk** [comment]
Actually I think since ODB no longer returns deleted observations this should no longer be necessary

**Comment by rpiaggio** [comment]
> Actually I think since ODB no longer returns deleted observations this should no longer be necessary

Agreed. Has the ODB behavior changed already?

**Comment by hugo-vrijswijk** [comment]
> > Actually I think since ODB no longer returns deleted observations this should no longer be necessary
> 
> Agreed. Has the ODB behavior changed already?

I think so yes. I'll update this PR tomorrow to remove the existence from the query and the existing check

**Review by rpiaggio — APPROVED** [review]
LGTM

**Pull request merged**
