### PR TITLE
Avoid table remounts in ObsSummaryTable and ObsAttachmentsTable

### PR DESCRIPTION
**Pull request by rpiaggio**
In ObsSumaryTable all data was moved to rows, in ObsAttachmentsTable we make use of `meta`.

### CODE REVIEW

**Review by hugo-vrijswijk — APPROVED** [review]
LGTM. I guess the main thing is not having to remount because only the meta changes?

**Comment by rpiaggio** [comment]
> LGTM. I guess the main thing is not having to remount because only the meta changes?

The components are remounted if the columns definitions change. So, the idea here is to avoid redefining the columns based on dependencies. If either the meta or the rows change, it will induce a rerender but not a remount.

**Review by toddburnside — APPROVED** [review]
LGTM. Thanks for taking care of this. It's nice to have an example for using table metadata now.

The summary seems to be: Recalculating rows or the TableOptions in `useReactTableBy` doesn't force a remount, but changing the columns does.

**Comment by toddburnside** [comment]
> LGTM. Thanks for taking care of this. It's nice to have an example for using table metadata now.
> 
> The summary seems to be: Recalculating rows or the TableOptions in `useReactTableBy` doesn't force a remount, but changing the columns does.

I see you already answered this above.

**Comment by rpiaggio** [comment]
Right. Ideally, the cols should be defined in a static `val`. Come thing of it, in that case maybe we don't even need to `useMemo` on it. I'll try that in the next PR.

**Pull request merged**
