### PR TITLE
Bundlemon

### PR DESCRIPTION
**Pull request by rpiaggio**
Let's see if this works...

### CODE REVIEW

**Comment by rpiaggio** [comment]
BTW, I evaluated, besides bundlemon: pkg-size, bundlewatch, bundlesize, size-limit, compressed-size-action.

Most were discarded because of the lack of ability to handle hashes in the file name.

**Comment by rpiaggio** [comment]
Also, enable brotli compression in static server.

**Review by toddburnside — APPROVED** [review]
👍 Great job.

**Comment by cquiroz** [comment]
Great work, I'm glad we have this back

**Pull request merged**
