### PR TITLE
Test inlining some code

### PR DESCRIPTION
**Pull request by cquiroz**
Mostly want to see the effect on js size

### CODE REVIEW

**Comment by cquiroz** [comment]
Hmm, it doesn't affect the size in any meaningful way

**Comment by rpiaggio** [comment]
> Hmm, it doesn't affect the size in any meaningful way

Maybe inlining was working with the annotation?

**Comment by cquiroz** [comment]
I guess that's probably right
Shall we merge this anyway?

**Review by rpiaggio — APPROVED** [review]
Yup, LGTM

**Pull request merged**
