### PR TITLE
Make fontawesome auth token secret env global to workflow

### PR DESCRIPTION
**Pull request by armanbilge**
Fixes https://github.com/gemini-hlsw/explore/issues/1504.

Btw, we could also just add this secret env globally to the whole workflow. Less secure, but then it's automatically applied to every step.

### CODE REVIEW

**Comment by cquiroz** [comment]
Less secure in the sense that a rogue action could steal it?

**Comment by armanbilge** [comment]
Yes, exactly.

**Comment by cquiroz** [comment]
I guess that's ok, we could put it on the whole workflow

**Review by cquiroz — APPROVED** [review]
Thanks LGTM

**Pull request merged**
