### PR TITLE
Avoid exception on ITC errors + show ITC rows again

### PR DESCRIPTION
**Pull request by rpiaggio**
An exception was being thrown to the console when logging an ITC call that resulted in an error. Errors are now logged via `Logger.debug`.

Should we log these errors via `Logger.error`? Or at least some of them?

The 2 types of errors I've seen so far are:
```
ITC: Result for mode Mode: GMOS-S, B600_G5323, Some(GPrime), IfuBlue: List(ERRORS: Chain(GenericError(Error calculating itc org.http4s.client.UnexpectedStatus: unexpected HTTP status: 400 Bad Request for request POST https://gemini-new-itc.herokuapp.com/json)))
```

and:
```
ITC: Result for mode Mode: GMOS-S, B600_G5323, None, Ifu2Slits: List(ERRORS: Chain(GenericError(Error calculating itc lucuma.itc.ItcCalculationError: S/N obtained is 0)))
```

### CODE REVIEW

**Comment by cquiroz** [comment]
Thanks for finding this. We should log the errors as they may help what's causing them

**Comment by rpiaggio** [comment]
> Thanks for finding this. We should log the errors as they may help what's causing them

Ok, I changed logging errors to `Logger.error`.

**Comment by rpiaggio** [comment]
Also added a fix to show ITC rows again. Basically, we need to add a CSS class when displaying virtualized tables (which would break them when they are regular `<table>`s).

**Review by cquiroz — APPROVED** [review]
LGTM, thanks

**Pull request merged**
