### PR TITLE
Use sttp cats fetch backend

### PR DESCRIPTION
**Pull request by cquiroz**
Just noted there is a cats-effect fetch backend recently introduced in sttp. This lets us have nicer code

### CODE REVIEW

**Review by rpiaggio — APPROVED** [review]
Nice LGTM.

BTW, there are other uses in `SSOClient`.

Maybe we should create a single `backend` and keep it in the context?

**Review by toddburnside — APPROVED** [review]
LGTM

**Comment by cquiroz** [comment]
Good point, I'll update the other bits as well

**Comment by rpiaggio** [comment]
Nice, you unified the backend too in SSO. Thank you!

**Pull request merged**
