### PR TITLE
New NewType

### PR DESCRIPTION
**Pull request by rpiaggio**
Adapt code to new lucuma-core's `NewType`

### CODE REVIEW

**Review by cquiroz — APPROVED** [review]
LGTM

**Comment by cquiroz** [comment]
Odd the size increased but i bet it is because the change in lucuma-core is not yet included?

**Review by toddburnside — APPROVED** [review]
LGTM

**Comment by rpiaggio** [comment]
> Odd the size increased but i bet it is because the change in lucuma-core is not yet included?

Ooops, I lost the lucuma-core update update in the rebase. Sending new commit.

**Comment by rpiaggio** [comment]
The size still increased, even with the latest lucuma-core, I wonder what's going on.

**Comment by cquiroz** [comment]
It is a `+543B` not a lot really

**Pull request merged**
