### PR TITLE
Make sequence table columns resizable

### PR DESCRIPTION
**Pull request by hugo-vrijswijk**

### CODE REVIEW

**Comment by hugo-vrijswijk** [comment]
@rpiaggio  I have not been able to reproduce this anymore. Are you able to?

https://github.com/gemini-hlsw/explore/assets/10114577/f57d634d-b226-4ccc-ae01-f9576e42d67f

**Comment by rpiaggio** [comment]
> @rpiaggio I have not been able to reproduce this anymore. Are you able to?
> 
>  Screen.Recording.2024-04-29.at.16.17.10.mov

I was just able to reproduce, resulting in
```
Uncaught Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
    at checkForNestedUpdates (react-dom.development.js:27292:11)
    at scheduleUpdateOnFiber (react-dom.development.js:25475:3)
    at dispatchSetState (react-dom.development.js:17527:7)
    at floating-ui.react.mjs:2747:7
    at $c_sjs_js_Any$.toFunction1__sjs_js_Function1__F1 (internal-030f6c8e2fcae469d98d99f878d74c0f1f80c6f9.js:73358:47)
    at $c_sjsr_AnonFunction1.apply__O__O (internal-030f6c8e2fcae469d98d99f878d74c0f1f80c6f9.js:73410:43)
    at $c_sjs_js_Any$.fromFunction1__F1__sjs_js_Function1 (internal-030f6c8e2fcae469d98d99f878d74c0f1f80c6f9.js:73352:29)
    at safelyDetachRef (react-dom.development.js:22908:22)
    at commitMutationEffectsOnFiber (react-dom.development.js:24351:13)
    at recursivelyTraverseMutationEffects (react-dom.development.js:24273:7)
```

The error happens after quite a bit of resizing different columns. I had to play for about 30s to get it to crash.

https://github.com/gemini-hlsw/explore/assets/1895643/faebedb3-3991-4067-ba0a-ef53fd9c3cf6

**Comment by rpiaggio** [comment]
BTW, I had repeated resizing of several columns for a bit before I captured the video.

**Comment by rpiaggio** [comment]
This was fixed when we changed the resize detector.

**Pull request closed without merging**
