### PR TITLE
Targets collapsed. Don't select on expand/collapse

### PR DESCRIPTION
**Pull request by rpiaggio**
[ch-570] [ch-577]

### CODE REVIEW

**Review by toddburnside — APPROVED** [review]
LGTM

**Comment by rpiaggio** [comment]
> LGTM

You beat me by a minute. I made some more changes since Andy requested expanded targets are remembered when navigating to another tab and returning.

**Comment by rpiaggio** [comment]
Also, this PR now fixes retrieving environment configuration when navigating to a URL other than the root.

**Comment by toddburnside** [comment]
> > LGTM
> 
> You beat me by a minute. I made some more changes since Andy requested expanded targets are remembered when navigating to another tab and returning.

Still looks good.

**Pull request merged**
